### PR TITLE
add routes and stub controllers

### PR DESCRIPTION
**Pull request by rejoycesong**
- added routes to `routes.rb` <-- just review this file
- added stub controllers, views

Routes list now look like (viewable via `bundle exec rake routes`):
https://pastebin.com/asrMWP21

1. PROJECTS routes:
-  PARTICIPANTS are **copied** from the ROSTER selected at project creation.
-  RANKING is the time ranking selected by the specific participant.
-  TIMES includes each datetime for the matching.
-  MATCHING is the final matching.

2. USERS routes: currently admins, may also include participants
3. ROSTERS routes: all rosters created by each user; this is different from PARTICIPANTS.

Examples:
- List all projects: `GET /projects/`
- Create project: `POST /projects/`
- Add new roster: `POST /rosters/`
- Add participants to a project: `POST /projects/{project_id}/participants/`
- Edit a participant of a project: `UPDATE /projects/{project_id}/participants/{participant_id}/edit`
- Add a time to a project: `POST /projects/{project_id}/times/`
- Remove a time from a project: `DELETE /projects/{project_id}/times/{the particular time}`
- Have participant submit their ranking for the first time: `POST /projects/{project_id}/participants/{participant_id}/ranking/`
- Have participant edit their ranking: `PATCH /projects/{project_id}/participants/{participant_id}/ranking/`

### CODE REVIEW

**Review by Turese — COMMENTED** [review]
It looks good! But I'm wondering why you changed the seeds.rb to make it so all the projects are by different users?

**Comment by rejoycesong** [comment]
> It looks good! But I'm wondering why you changed the seeds.rb to make it so all the projects are by different users?

Haha I was trying to debug an error. :( I reverted the change in a later commit - https://github.com/Aakup/MultiMeet-1/pull/5/commits/24fca246cecc9f0d1ff6abf5aa73758718dfad7d

**Comment by kev-chien** [comment]
@jsluong could you clarify on rosters? Is the idea for roster to be like just a list of participants that you can add to each project if projects have the same rosters? Just wanted to make sure, thanks!

I originally didn't design for rosters to be separate from participants, and only created a participants table, but if the intention is to be able to store rosters separately I can add a table in the future.

**Review by kev-chien — DISMISSED** [review]
Looks good! I really like the use of nested resources, it looks very clean. The URL design makes a lot of sense to me.

Per mockup page 5a and 5b, I think we'd like to be able to add dates in addition to timestamps (where each timestamp references a date). Hence the Project_Dates table and the Project_Times table. Could you add dates as another resource under projects? Or let me know your thoughts. Thank you!

**Comment by rejoycesong** [comment]
> @jsluong could you clarify on rosters? Is the idea for roster to be like just a list of participants that you can add to each project if projects have the same rosters? Just wanted to make sure, thanks!

This is exactly it; re: mockups 6a, where a user is able to reuse rosters from different projects. 

> I originally didn't design for rosters to be separate from participants, and only created a participants table, but if the intention is to be able to store rosters separately I can add a table in the future.

I didn't anticipate separating them, either, but then I realized that if we wanted to maintain the functionality shown in the mockups (being able to reuse rosters), we'd have to keep it separate. 

Alternatively, I wondered why we would keep rosters separate but not times/dates. Given this, I'm perfectly okay with merging them together again. There's no reason why we should be able to reuse one but not the other. What are your thoughts @kev-chien?

> Per mockup page 5a and 5b, I think we'd like to be able to add dates in addition to timestamps (where each timestamp references a date). Hence the Project_Dates table and the Project_Times table. Could you add dates as another resource under projects? Or let me know your thoughts. > Thank you!

I sat on this for quite a long time. I was thinking initially that `times` gets nested under `dates` which is nested under `projects`, which would have made the route long. But you're suggesting to keep them both on the same level under `projects`--why? That's fine with me re: not keeping the route too long, but it makes more sense to me to nest `times` under `dates`. Thoughts?

**Comment by kev-chien** [comment]
> I didn't anticipate separating them, either, but then I realized that if we wanted to maintain the functionality shown in the mockups (being able to reuse rosters), we'd have to keep it separate.

> Alternatively, I wondered why we would keep rosters separate but not times/dates. Given this, I'm perfectly okay with merging them together again. There's no reason why we should be able to reuse one but not the other. What are your thoughts @kev-chien?

I didn't notice the functionality in 6a, thanks for pointing it out! Since it's in the mockup I'm all for creating another rosters table, and we can leave this resource in the routes. We probably need to create another table RostersEntry to be able to store entries in rosters, but since in this iteration we are only doing manual rosters (without importing) (6b), I think we can leave that for a future iteration.

> I sat on this for quite a long time. I was thinking initially that times gets nested under dates which is nested under projects, which would have made the route long. But you're suggesting to keep them both on the same level under projects--why? That's fine with me re: not keeping the route too long, but it makes more sense to me to nest times under dates. Thoughts?

I think you have a great point with nesting times under dates, it makes more sense since times belong to dates. I was thinking what the end URL would look like: for 5a), we could display all the dates via `GET /projects/{id]/dates/`, whereas with 5b it makes sense to display all the times via `GET /projects/{id}/times/` since the mockup displays all the times available instead of only displaying one for each date.

So ultimately I agree that we should put `resources times` under `resources dates`, but then we'd need another controller e.g. TimesMasterController that allows for 5b or displaying all the times at once (`GET /projects/{id}/times/`) and hides those internal calls, e.g. in routes.rb we could add under `resources projects` the line `get /times -> 'timesmaster#index'` And then in TimesMasterController/ view we can do internal GET and POST calls, that use the full nested URL e.g. `POST /projects/{id}/dates/{id}/times`, but we could hide the URL via internal calls and redirects. @jsluong what do you think?

**Review by kev-chien — DISMISSED** [review]
- [ ] Move resources :times under resources :dates

**Review by kev-chien — APPROVED** [review]
Looks good! Sorry for long discussion.

**Pull request merged**
