### PR TITLE
Aaron/update time

### PR DESCRIPTION
**Pull request by Aakup**

### CODE REVIEW

**Review by alined908 — APPROVED** [review]
aaron this works as intended. great job!

**Comment by rejoycesong** [comment]
Looks great overall, Aaron! It seems like you're able to select times that are already taken though?
Also line break issues:
image

**Review by kev-chien — APPROVED** [review]
Looks good! Works as expected, I really like how you implemented the dropdown menu. Thanks~

**Comment by Aakup** [comment]
Thx for all the great comments! I will make some changes later before Monday, but I will merge this pr now for Sunday review.

**Pull request merged**
