### PR TITLE
Kevin/responsive

### PR DESCRIPTION
**Pull request by kev-chien**
Made projects#index more responsive using bootstrap grid columns instead of % of width.

### CODE REVIEW

**Review by lawrencechen14 — COMMENTED** [review]
Screen Shot 2019-05-14 at 12 57 24 AM

Seems like there could be a couple things to fix here, like adding some padding to the text to the left and making the "Add New Project" font bigger to fill the box. Also, I personally liked it better when "Add New Project" had its own row.

Another small thing, it seems like the navbar has color code #fffafa, so it is slightly red. Is this intentional?

**Review by Aakup — APPROVED** [review]
Good job

**Comment by kev-chien** [comment]
> Seems like there could be a couple things to fix here, like adding some padding to the text to the left and making the "Add New Project" font bigger to fill the box. Also, I personally liked it better when "Add New Project" had its own row.
> 
> Another small thing, it seems like the navbar has color code #fffafa, so it is slightly red. Is this intentional?

Padding now added. Other stylistic choices were discussed offline.

**Review by lawrencechen14 — APPROVED** [review]
Looks good, thanks for the changes!

**Pull request merged**
