### PR TITLE
Daniel/css

### PR DESCRIPTION
**Pull request by alined908**
- make ui consistent

### CODE REVIEW

**Comment by kev-chien** [comment]
Sorry I wanted to approve this but was busy, this looks good we should still merge it in!

**Review by kev-chien — APPROVED** [review]
Thanks for making the UI more consistent! And for helping make some parts more intuitive to use (like explaining match degree)!

**Comment by alined908** [comment]
Please don't merge yet, adding some more commits to make everything mobile responsive

**Comment by kev-chien** [comment]
I made a few changes:

- table email now word wraps, from table-layout: fixed (so looks better on smaller screen + the columns are always evenly sized)
- "add manually" and "import csv" start out 50% (using bootstrap columns), then become their own rows on smaller screens
- add manually email field gets it's own entire row, so that it's easier for users to input email and see the entire email as they type. Previously in this PR it beame "email", "match_degree", and "add participant" in the same row which made it hard to see the entire email when typing it in.

My changes:

Screen Shot 2019-05-20 at 8 40 22 AM

Previously:

Screen Shot 2019-05-20 at 8 44 58 AM

**Comment by alined908** [comment]
thanks kevin for the suggested change! The change is committed on daniel/responsive branch. I think for the table, how it looked before was alright, but let me know if you think otherwise. Going to close this pr now

**Pull request closed without merging**
